### ISSUE TITLE
Lock in numbers that have been entered. 

### ISSUE THREAD

**Issue by jacksnodgrass** [ogarcia/opensudoku#14]
I don't generally use notes. I just enter in the correct number in a square. Occasionally I will press the wrong square or the wrong square will be selected and I'l over-write the previously entered, correct number. I can sometimes do undo ( if I remember ) but sometimes I have issues getting back to where I was before the wrong number overwrote the correct number. 

I'd like a game mode where you get a "are you sure" when you are over writing a previously entered number.  If I enter a 5.. it's a 5.  It should take a prompt for me to change it to a 6. 

- jack

**Comment by leogott** [comment]
I personally use the SingleNumber input mode and would love an **option in the settings** that changes the behaviour of SN as follows:

- Do not change the selected number by tapping a number in the grid (Regarless of Pencilmark on/off and C or number selected)

- Do not write over a writeable number with a different one, instead do nothing. (Except with C selected)

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 31.

WARNING: It is important that you don't do it immediately and wait until July 31 because what I currently have in GitLab can be deleted.

Thank you very much for your understanding.
