### ISSUE TITLE
[FR] Add an option to skip new title screen

### ISSUE THREAD

**Issue by ogarcia** [ogarcia/opensudoku#65]
@jlnordin Seems that the new title screen does not like to everyone. There is some people that prefers that the app starts directly in sudoku list.
Do you think that could add a new option to skip it? Thanks in advance.

**Comment by jlnordin** [comment]
Shouldn't be a problem. I'll take a look.

**Comment by Forage** [comment]
The change has been made already, but in my opinion it would have been a better to decide on a better default instead of adding more options. There's already plenty of options for such a simple game.

The title screen does not add much but an extra redundant step.
The settings page should not be so important to merit a direct link on the first screen you see.
The resume button magically appears when you didn't finish a game. Disabling instead of hiding would be one option to make the UI more predictable/stable, but the fact that it's behaviour is unpredictable when active as well should be enough reason to not have it at all. What happens if you haven't finished multiple games? You can't really know unless you start tracking back to where it takes you.
Which leaves us with the only usable option: the button to the lists screen. And that just happens to be first screen we had without the new start screen ;-)

**Comment by jlnordin** [comment]
@Forage , thanks for the thoughtful write up.

I added the title screen feature, so I wanted to chime in. "Resume" is one of the most important features for me personally since I like to work on the same puzzle for short bursts during the day. In my case it actually cuts down the number of clicks to get back to what I was doing, and that was the primary motivation behind the title screen. Another Sudoku app I use, which is otherwise excellent, doesn't have this feature and I've really wanted it, which is why I added it to Open Sudoku. :-)

Changing the "resume" button to be disabled is a possibility. I chose to hide it based on how other Sudoku games treat their title screens.

And just to address the multiple-unfinished-games question, "resume" takes you to the game you were most recently playing. If you finish a game it doesn't automatically pick a different unfinished game -- it currently requires player intention.

And if you have any other feature requests or bugs, please let me know!
