### ISSUE TITLE
Bidirectional selection enabled despite turned off in settings

### ISSUE THREAD

**Issue by slowan** [ogarcia/opensudoku#71]
When field is selected (no matter if editable or not) the corresponding button is highlighted despite the setting is off.
![Screenshot_20200328-141249_Open Sudoku](https://user-images.githubusercontent.com/60142747/77823834-70852700-70fe-11ea-8803-e607222f91b0.jpg)
![Screenshot_20200328-141401_Open Sudoku](https://user-images.githubusercontent.com/60142747/77823836-71b65400-70fe-11ea-8743-c4b063ef29ad.jpg)
![Screenshot_20200328-141300_Open Sudoku](https://user-images.githubusercontent.com/60142747/77823837-724eea80-70fe-11ea-90f9-9643078c7ba4.jpg)
![Screenshot_20200328-141310_Open Sudoku](https://user-images.githubusercontent.com/60142747/77823838-72e78100-70fe-11ea-961e-97f25d6c304c.jpg)

**Comment by slowan** [comment]
It is quite annoying as it looks similar to greyed button for numbers present more than 9 times.

**Comment by jlnordin** [comment]
Slowan,

That option only applies to single number input mode -- num pad mode will
always show the current number because that's how that input mode works. It
will show the current state of the number or the notes (if notes mode is
active).

Can you describe how you expect it to work? If so, we might be able to add
a feature to make it work better for you.

As for the colors, I added them in and tried to make the contrast between
highlighted numbers and completed numbers as clear as possible, but some
themes are clearer than others. If you want to make the distinction clearer
on your own game you can create a custom theme based on the open Sudoku
theme and change the button highlight color to whatever you like.

**Comment by ogarcia** [comment]
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.
